on:
  push:
    branches:
      - assignments-new
    # paths: ['**.Rmd']

name: Render and Publish Website

permissions:
  contents: write
  pages: write

jobs:
  render-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_ACTION }}

      - name: Check out private repo with assignments
        uses: actions/checkout@v4
        with:
          repository: 'andrjohns/bda_course'
          ref: 'infra'
          path: 'bda_course'
          fetch-depth: 1
          token: ${{ secrets.GH_ACTION }}

      - name: Copy assignments
        run: cp -r bda_course/assignments/ assignments/

      - name: List files
        run: ls -l assignments/
